// Size-chart export — JSON / CSV / PDF. Pure browser (no new dependency): PDF is rendered via a
// styled print window (Save as PDF). The chart is the AI-generated GeneratedChart from lib/grading.
import type { GeneratedChart, GradeDim } from "./grading";

const DIM_LABELS: Record<GradeDim, string> = {
  chest_cm: "Chest (cm)",
  waist_cm: "Waist (cm)",
  length_cm: "Length (cm)",
  shoulder_cm: "Shoulder (cm)",
  sleeve_cm: "Sleeve (cm)",
};

const ALL_DIMS: GradeDim[] = ["chest_cm", "waist_cm", "length_cm", "shoulder_cm", "sleeve_cm"];

export interface ChartMeta {
  garmentType?: string | null;
  category?: string;
  confidence?: number; // 0..1 overall
}

/** Dimensions that actually have measured values in this chart. */
export function activeDims(chart: GeneratedChart): GradeDim[] {
  return ALL_DIMS.filter((d) => chart.sizes.some((r) => r[d] !== undefined));
}

function triggerDownload(filename: string, mime: string, content: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function baseName(meta: ChartMeta): string {
  const t = (meta.garmentType || meta.category || "garment").toString().toLowerCase().replace(/\s+/g, "-");
  return `asli-size-chart-${t}`;
}

export function exportChartJSON(chart: GeneratedChart, meta: ChartMeta): void {
  const payload = {
    generatedBy: "Asli Smart Sizing (Agent 2)",
    garmentType: meta.garmentType ?? null,
    category: meta.category ?? null,
    anchoredOn: chart.anchoredOn,
    sizedBy: chart.sizedBy,
    overallConfidence: meta.confidence ?? null,
    dimensions: activeDims(chart),
    sizes: chart.sizes,
  };
  triggerDownload(`${baseName(meta)}.json`, "application/json", JSON.stringify(payload, null, 2));
}

export function exportChartCSV(chart: GeneratedChart, meta: ChartMeta): void {
  const dims = activeDims(chart);
  const header = ["Size", ...dims.map((d) => DIM_LABELS[d])].join(",");
  const rows = chart.sizes.map((r) =>
    [r.size, ...dims.map((d) => (r[d] !== undefined ? r[d] : ""))].join(","),
  );
  const note = `# Asli Smart Sizing — ${meta.garmentType ?? meta.category ?? "garment"}` +
    (meta.confidence != null ? ` (confidence ${Math.round(meta.confidence * 100)}%)` : "") +
    `, measured anchor size ${chart.anchoredOn}`;
  triggerDownload(`${baseName(meta)}.csv`, "text/csv", [note, header, ...rows].join("\n"));
}

const esc = (s: unknown): string =>
  String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string);

export function exportChartPDF(chart: GeneratedChart, meta: ChartMeta): void {
  const dims = activeDims(chart);
  const head = `<th>Size</th>` + dims.map((d) => `<th>${esc(DIM_LABELS[d])}</th>`).join("");
  const body = chart.sizes
    .map((r) => {
      const anchor = r.size === chart.anchoredOn;
      const cells = `<td><b>${r.size}</b>${anchor ? " ✓ measured" : ""}</td>` +
        dims.map((d) => `<td>${r[d] !== undefined ? r[d] : "—"}</td>`).join("");
      return `<tr class="${anchor ? "anchor" : ""}">${cells}</tr>`;
    })
    .join("");
  const conf = meta.confidence != null ? `Confidence ${Math.round(meta.confidence * 100)}%` : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Asli Size Chart</title>
    <style>
      body{font-family:system-ui,Arial,sans-serif;color:#111;padding:32px}
      h1{margin:0 0 4px;font-size:20px} .sub{color:#666;margin-bottom:16px;font-size:13px}
      table{border-collapse:collapse;width:100%;font-size:13px}
      th,td{border:1px solid #ddd;padding:8px 10px;text-align:center}
      th{background:#f5f0fb;text-transform:uppercase;font-size:11px;letter-spacing:.04em}
      tr.anchor{background:#eafaef;font-weight:600}
      .foot{margin-top:16px;color:#999;font-size:11px}
    </style></head><body>
    <h1>Asli — AI-Measured Size Chart</h1>
    <div class="sub">${meta.garmentType ?? meta.category ?? "Garment"} · measured anchor size <b>${chart.anchoredOn}</b> · sized by ${chart.sizedBy.replace("_cm", "")} · ${conf}</div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="foot">Generated by Asli Smart Sizing (Agent 2) — measured from an A4 reference, graded by industry increments. Not guessed.</div>
    </body></html>`;
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}
